### PR TITLE
Add ansible-role-rsyslog, fix typos

### PR DESCRIPTION
**Pull request by papanito**
I added my ansible role to the list and fixed some typos.

### CODE REVIEW

**Comment by papanito** [comment]
@DanielBerman are you looking at prs?

**Comment by roiravhon** [comment]
Hi @papanito thanks!
Daniel is not working in Logz.io anymore (Unfortunately!!! @DanielBerman ❤️ )

@Doron-Bargo is the current address

**Comment by papanito** [comment]
@roiravhon thanks for letting me know. Was not sure if the pr will be seen ;-)

**Comment by papanito** [comment]
@Doron-Bargo may you have a chance to look at it?

**Review by Doron-Bargo — APPROVED** [review]

**Comment by papanito** [comment]
Thanks

**Pull request merged**
